googleAnalytics {
  enabled = true
}

trends {
  windowDays = 21
}

staticAssets {
  jsCache {
    enabled = true
    maxAgeSeconds = 3600
  }
  cssCache {
    enabled = true
    maxAgeSeconds = 3600
  }
}
