googleAnalytics {
  enabled = false
}

trends {
  windowDays = 21
}

staticAssets {
  jsCache {
    enabled = false
    maxAgeSeconds = 3600
  }
  cssCache {
    enabled = false
    maxAgeSeconds = 3600
  }
}

