googleAnalytics {
  enabled = true
}

trends {
  windowDays = 40
}

staticAssets {
  minified = true
  jsCache {
    enabled = true
    maxAgeSeconds = 3600
  }
  cssCache {
    enabled = true
    maxAgeSeconds = 3600
  }
}
